In [1]:
import pandas as pd
import numpy as np

### Ejercicio II

#### Pregunta 1

In [225]:
#requiere argumento sep = ";"
dolar_2019=pd.read_csv("https://raw.githubusercontent.com/hfas85/tarea1-add/master/data/raw/dolar2019_sii.csv",sep=";")

#### Pregunta 2

In [172]:
#requiere argumento sep="|" y names = nombre de las columnas
columns1=dolar_2019.columns

dolar_2020_txt=pd.read_csv("https://raw.githubusercontent.com/hfas85/tarea1-add/master/data/raw/dolar_2020_sii.txt",sep="|",
                           names=columns1, header=None)

In [113]:
dolar_2020_txt.head()

Día     Ene     Feb     Mar     Abr     May     Jun     Jul     Ago     Sep  \
0   1     NaN     NaN     NaN  852,03     NaN  806,32  821,23     NaN  776,46   
1   2  748,74     NaN  818,32  863,81     NaN  796,46  816,29     NaN  770,59   
2   3  754,16  799,11  817,45  861,89     NaN  782,86  803,98  757,06  771,45   
3   4     NaN  790,92  809,81     NaN  837,92  769,13     NaN  761,34  773,71   
4   5     NaN  781,78  812,19     NaN  838,74  775,58     NaN  767,98     NaN   

      Oct     Nov     Dic  
0  788,15     NaN  767,29  
1  785,04  771,92  760,16  
2     NaN  769,17  755,34  
3     NaN  758,53  752,03  
4  790,81  757,16     NaN

#### Pregunta 3

In [173]:
dolar_2020_regex=pd.read_csv("https://raw.githubusercontent.com/hfas85/tarea1-add/master/data/raw/dolar_2020_sii_AA.dat",
                              sep='[X]', engine='python',header=None)  

In [115]:
dolar_2020_regex.head()

0  1       2  3       4  5       6  7       8  9   ... 15      16 17  \
0  1  A     NaN  A     NaN  A     NaN  A  852,03  A  ...  A     NaN  A   
1  2  B  748,74  B     NaN  B  818,32  B  863,81  B  ...  B     NaN  B   
2  3  B  754,16  Z  799,11  Z  817,45  Z  861,89  Z  ...  Z  757,06  Z   
3  4  Z     NaN  t  790,92  t  809,81  t     NaN  t  ...  t  761,34  t   
4  5  t     NaN  t  781,78  t  812,19  t     NaN  t  ...  t  767,98  t   

       18 19      20 21      22 23      24  
0  776,46  A  788,15  A     NaN  A  767,29  
1  770,59  B  785,04  B  771,92  B  760,16  
2  771,45  Z     NaN  Z  769,17  Z  755,34  
3  773,71  t     NaN  t  758,53  t  752,03  
4     NaN  t  790,81  t  757,16  t     NaN  

[5 rows x 25 columns]

In [174]:
num=[]
for i in range(0,24):
    if i & 1 != 0:
        num.append(i)

dolar_2020_regex=dolar_2020_regex.drop(dolar_2020_regex.columns[num],axis=1)

In [175]:
dolar_2020_regex.columns =columns1
dolar_2020_regex.head()

Día     Ene     Feb     Mar     Abr     May     Jun     Jul     Ago     Sep  \
0   1     NaN     NaN     NaN  852,03     NaN  806,32  821,23     NaN  776,46   
1   2  748,74     NaN  818,32  863,81     NaN  796,46  816,29     NaN  770,59   
2   3  754,16  799,11  817,45  861,89     NaN  782,86  803,98  757,06  771,45   
3   4     NaN  790,92  809,81     NaN  837,92  769,13     NaN  761,34  773,71   
4   5     NaN  781,78  812,19     NaN  838,74  775,58     NaN  767,98     NaN   

      Oct     Nov     Dic  
0  788,15     NaN  767,29  
1  785,04  771,92  760,16  
2     NaN  769,17  755,34  
3     NaN  758,53  752,03  
4  790,81  757,16     NaN

#### Pregunta 4

In [176]:
#forma de los data frames
np.shape(dolar_2019),np.shape(dolar_2020_txt),np.shape(dolar_2020_regex)

((32, 13), (32, 13), (32, 13))

In [177]:
#elimina la ultima fila 
dolar_2019=dolar_2019.drop(31)
dolar_2020_txt=dolar_2020_txt.drop(31)
dolar_2020_regex=dolar_2020_regex.drop(31)

In [178]:
#forma de los data frames
np.shape(dolar_2019),np.shape(dolar_2020_txt),np.shape(dolar_2020_regex)

((31, 13), (31, 13), (31, 13))

In [179]:
#Mismos nombres de columnas para los data frames
dolar_2019.columns,dolar_2020_txt.columns,dolar_2020_regex.columns

(Index(['Día', 'Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep',
        'Oct', 'Nov', 'Dic'],
       dtype='object'),
 Index(['Día', 'Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep',
        'Oct', 'Nov', 'Dic'],
       dtype='object'),
 Index(['Día', 'Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep',
        'Oct', 'Nov', 'Dic'],
       dtype='object'))

In [181]:
#agrega campo year a cada data frame
dolar_2019["year"]= 2019
dolar_2020_txt["year"]= 2020
dolar_2020_regex["year"]= 2020

In [182]:
#el campo year tiene formato int64 en los data frames
dolar_2019["year"].unique(),dolar_2020_txt["year"].unique(),dolar_2020_regex["year"].unique()

(array([2019], dtype=int64),
 array([2020], dtype=int64),
 array([2020], dtype=int64))

In [183]:
#convertir comas a puntos
dolar_2019.iloc[:,1:13]=dolar_2019.iloc[:,1:13].stack().str.replace(',','.').unstack().astype(float)
dolar_2020_txt.iloc[:,1:13]=dolar_2020_txt.iloc[:,1:13].stack().str.replace(',','.').unstack().astype(float)
dolar_2020_regex.iloc[:,1:13]=dolar_2020_regex.iloc[:,1:13].stack().str.replace(',','.').unstack().astype(float)

In [193]:
#Convertir campos str a int
dolar_2019.iloc[:,0]=dolar_2019.iloc[:,0].astype(int)
dolar_2020_txt.iloc[:,0]=dolar_2020_txt.iloc[:,0].astype(int)
dolar_2020_regex.iloc[:,0]=dolar_2020_regex.iloc[:,0].astype(int)

In [199]:
#Todos los campos quedan en int o float
dolar_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Día     31 non-null     int32  
 1   Ene     22 non-null     float64
 2   Feb     20 non-null     float64
 3   Mar     21 non-null     float64
 4   Abr     21 non-null     float64
 5   May     21 non-null     float64
 6   Jun     20 non-null     float64
 7   Jul     22 non-null     float64
 8   Ago     21 non-null     float64
 9   Sep     18 non-null     float64
 10  Oct     22 non-null     float64
 11  Nov     20 non-null     float64
 12  Dic     20 non-null     float64
 13  year    31 non-null     int64  
dtypes: float64(12), int32(1), int64(1)
memory usage: 3.4 KB


#### Pregunta 5

In [201]:
#transformar dfs a archivos planos
dolar_2019.to_csv("d2019.csv",sep=",")
dolar_2020_txt.to_csv("d2020.txt",sep=" ")
dolar_2020_regex.to_csv("dolar_2020_excel.csv",sep=";")

#### Pregunta 6

In [205]:
df_concat_1= pd.concat((dolar_2019,dolar_2020_txt),axis=1)
df_concat_0= pd.concat((dolar_2019,dolar_2020_txt),axis=0)

In [212]:
#el problema en df_concat_1 es que se repiten los nombres de las columnas. Si quisieramos seleccionar algún(os) mes(es)
#en especifico no sabriamos a que año corresponde(n) 
df_concat_1.head()

Día     Ene     Feb     Mar     Abr     May     Jun     Jul     Ago  \
0    1     NaN  657.81  651.79  678.53     NaN     NaN  679.15  700.82   
1    2  694.77     NaN     NaN  672.56  678.71     NaN  677.62  704.88   
2    3  697.09     NaN     NaN  670.05  683.31  709.80  681.30     NaN   
3    4  697.64  655.39  656.57  667.55     NaN  704.59  680.48     NaN   
4    5     NaN  653.80  659.07  666.32     NaN  696.78  677.64  711.13   

      Sep  ...     Abr     May     Jun     Jul     Ago     Sep     Oct  \
0     NaN  ...  852.03     NaN  806.32  821.23     NaN  776.46  788.15   
1  720.20  ...  863.81     NaN  796.46  816.29     NaN  770.59  785.04   
2  724.72  ...  861.89     NaN  782.86  803.98  757.06  771.45     NaN   
3  725.69  ...     NaN  837.92  769.13     NaN  761.34  773.71     NaN   
4  723.30  ...     NaN  838.74  775.58     NaN  767.98     NaN  790.81   

      Nov     Dic  year  
0     NaN  767.29  2020  
1  771.92  760.16  2020  
2  769.17  755.34  2020  
3  758.53  752.03  2020  
4  757.16     NaN  2020  

[5 rows x 28 columns]

In [223]:
#el problema en df_concat_2 es que se repiten los indices de las filas. Si quisieramos seleccionar algún(os) registro(s)
# de un día determinado habría que filtrar por el campo year.
df_concat_0[df_concat_0["Día"]==13]

Día     Ene     Feb     Mar     Abr     May     Jun     Jul     Ago  \
12   13     NaN  660.49  667.09     NaN  685.67  694.89     NaN  716.69   
12   13  770.56  788.33  852.06  839.49  821.88     NaN  790.82  792.69   

       Sep     Oct     Nov     Dic  year  
12  711.29     NaN  783.72  768.69  2019  
12     NaN  796.05  757.43     NaN  2020